baseURL = 'https://ndlrfz.web.id/'
languageCode = 'en-us'
title = 'Nadlir Blog'
theme = 'PaperMod'

[params]
env = "production"
author = ["Nadlir"]
ShowToc = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowPageNums = true

[params.assets]
favicon = "https://ndlrfz.github.io/blog/favicon.ico"
favicon16x16 = "https://ndlrfz.github.io/blog/favicon.ico"
favicon32x32 = "https://ndlrfz.github.io/blog/favicon.ico"
apple_touch_icon = "https://ndlrfz.github.io/blog/favicon.ico"
safari_pinned_tab = "https://ndlrfz.github.io/blog/favicon.ico"

[params.homeInfoParams]
Title = "Ndlrfz ğŸ§ğŸ® ğŸ¦„"
Content = """**You will become clever through your mistakes.**
_â€”German proverb_
"""

